# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Lanyon
tagline:          'A Jekyll theme'
description:      'A reserved <a href="http://jekyllrb.com" target="_blank">Jekyll</a> theme that places the utmost gravity on content with a hidden drawer. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:              http://lanyon.getpoole.com
baseurl:          ''

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         5

exclude:          [README.md, LICENSE.md]

# Custom vars
github:
  repo:           https://github.com/poole/lanyon
  version:        v1.0.0
